<?php

namespace Structural\Decorator;

class BigTrouser extends Finery
{
    public function show()
    {
        print_r("跨裤\n");
        parent::show(); // TODO: Change the autogenerated stub
    }
}