<?php

namespace Structural\Decorator;

class Sneakers extends Finery
{
    public function show()
    {
        print_r("破球鞋\n");
        parent::show(); // TODO: Change the autogenerated stub
    }
}