<?php

namespace Structural\Decorator;

class TShirts extends Finery
{
    public function show()
    {
        print_r("大T恤\n");
        parent::show(); // TODO: Change the autogenerated stub
    }
}